#!/usr/bin/env bash
set -euo pipefail

DEFAULT_REPO="https://github.com/Kuaizr/llm_api_factory.git"
DEFAULT_REF="main"

WS_URL=""
HEARTBEAT_URL=""
AGENT_NAME=""
AGENT_TOKEN=""
AGENT_REGION=""
AGENT_NETWORK_GROUP=""
AGENT_LABELS=""
AGENT_ENDPOINT_URL=""
AGENT_ALLOWED_TARGETS=""
REPO_URL="${LLM_AGENT_INSTALL_REPO_URL:-$DEFAULT_REPO}"
REPO_REF="${LLM_AGENT_INSTALL_REPO_REF:-$DEFAULT_REF}"
INSTALL_DIR="${LLM_AGENT_INSTALL_DIR:-}"
NO_SYSTEMD=0

usage() {
  cat <<'EOF'
Install and start an llm_api_factory agent.

Usage:
  curl -fsSL <agent_install.sh> | bash -s -- \
    --ws-url ws://control.example.com/agent/ws \
    --heartbeat-url http://control.example.com/agent/heartbeat \
    --agent-name edge-vps \
    --agent-token <token>

Options:
  --ws-url <url>                 Control-plane WebSocket URL. Required.
  --heartbeat-url <url>          Control-plane HTTP heartbeat URL.
  --agent-name <name>            Agent node name. Required.
  --agent-token <token>          Agent token generated by the console. Required.
  --agent-region <region>        Optional region label.
  --agent-network-group <group>  Optional network group label.
  --agent-labels <csv>           Optional comma-separated labels.
  --agent-endpoint-url <url>     Optional public endpoint metadata.
  --allowed-targets <list>       Comma-separated URL target allowlist for proxying.
  --repo <url>                   Git repository to clone.
  --repo-ref <ref>               Git branch/tag/commit to checkout.
  --install-dir <path>           Install directory.
  --no-systemd                   Run with nohup instead of systemd.
  --help                         Show this help.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ws-url)
      WS_URL="$2"
      shift 2
      ;;
    --heartbeat-url)
      HEARTBEAT_URL="$2"
      shift 2
      ;;
    --agent-name)
      AGENT_NAME="$2"
      shift 2
      ;;
    --agent-token)
      AGENT_TOKEN="$2"
      shift 2
      ;;
    --agent-region)
      AGENT_REGION="$2"
      shift 2
      ;;
    --agent-network-group)
      AGENT_NETWORK_GROUP="$2"
      shift 2
      ;;
    --agent-labels)
      AGENT_LABELS="$2"
      shift 2
      ;;
    --agent-endpoint-url)
      AGENT_ENDPOINT_URL="$2"
      shift 2
      ;;
    --allowed-targets)
      AGENT_ALLOWED_TARGETS="$2"
      shift 2
      ;;
    --repo)
      REPO_URL="$2"
      shift 2
      ;;
    --repo-ref)
      REPO_REF="$2"
      shift 2
      ;;
    --install-dir)
      INSTALL_DIR="$2"
      shift 2
      ;;
    --no-systemd)
      NO_SYSTEMD=1
      shift
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$WS_URL" || -z "$AGENT_NAME" || -z "$AGENT_TOKEN" ]]; then
  echo "Missing required arguments: --ws-url, --agent-name, --agent-token" >&2
  usage
  exit 1
fi

if [[ -z "$INSTALL_DIR" ]]; then
  if [[ "${EUID:-$(id -u)}" -eq 0 ]]; then
    INSTALL_DIR="/opt/llm-api-factory-agent"
  else
    INSTALL_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/llm-api-factory-agent"
  fi
fi

require_command() {
  local command_name="$1"
  if ! command -v "$command_name" >/dev/null 2>&1; then
    echo "Missing required command: $command_name" >&2
    exit 1
  fi
}

install_system_packages_if_possible() {
  if command -v git >/dev/null 2>&1 && command -v curl >/dev/null 2>&1; then
    return
  fi
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    return
  fi

  if command -v apt-get >/dev/null 2>&1; then
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y git curl ca-certificates
  elif command -v pacman >/dev/null 2>&1; then
    pacman -Sy --noconfirm --needed git curl ca-certificates
  elif command -v dnf >/dev/null 2>&1; then
    dnf install -y git curl ca-certificates
  elif command -v yum >/dev/null 2>&1; then
    yum install -y git curl ca-certificates
  elif command -v apk >/dev/null 2>&1; then
    apk add --no-cache git curl ca-certificates
  fi
}

install_uv_if_needed() {
  if command -v uv >/dev/null 2>&1; then
    return
  fi
  require_command curl
  echo "Installing uv..."
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="$HOME/.local/bin:$PATH"
  if ! command -v uv >/dev/null 2>&1; then
    echo "uv installation failed or uv is not on PATH" >&2
    exit 1
  fi
}

sync_repo() {
  require_command git
  local clone_ref="${REPO_REF#refs/heads/}"
  if [[ -d "$INSTALL_DIR/.git" ]]; then
    echo "Updating repository in $INSTALL_DIR"
    git -C "$INSTALL_DIR" fetch origin --prune
    git -C "$INSTALL_DIR" checkout "$clone_ref" 2>/dev/null || git -C "$INSTALL_DIR" checkout "$REPO_REF"
    git -C "$INSTALL_DIR" pull --ff-only origin "$clone_ref" 2>/dev/null || true
    return
  fi

  if [[ -e "$INSTALL_DIR" ]]; then
    echo "Install directory exists but is not a git repository: $INSTALL_DIR" >&2
    exit 1
  fi

  echo "Cloning $REPO_URL into $INSTALL_DIR"
  mkdir -p "$(dirname "$INSTALL_DIR")"
  if ! git clone --depth 1 --branch "$clone_ref" "$REPO_URL" "$INSTALL_DIR"; then
    git clone "$REPO_URL" "$INSTALL_DIR"
    git -C "$INSTALL_DIR" checkout "$REPO_REF"
  fi
}

env_quote() {
  local value="$1"
  value="${value//$'\r'/}"
  value="${value//$'\n'/}"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "$value"
}

write_env_var() {
  local name="$1"
  local value="$2"
  printf "%s=" "$name"
  env_quote "$value"
  printf "\n"
}

write_env_file() {
  local env_file="$1"
  : >"$env_file"
  write_env_var "LLM_AGENT_WS_URL" "$WS_URL" >>"$env_file"
  if [[ -n "$HEARTBEAT_URL" ]]; then
    write_env_var "LLM_AGENT_HEARTBEAT_URL" "$HEARTBEAT_URL" >>"$env_file"
  fi
  write_env_var "LLM_AGENT_NAME" "$AGENT_NAME" >>"$env_file"
  write_env_var "LLM_AGENT_AUTH_TOKEN" "$AGENT_TOKEN" >>"$env_file"
  if [[ -n "$AGENT_REGION" ]]; then
    write_env_var "LLM_AGENT_REGION" "$AGENT_REGION" >>"$env_file"
  fi
  if [[ -n "$AGENT_NETWORK_GROUP" ]]; then
    write_env_var "LLM_AGENT_NETWORK_GROUP" "$AGENT_NETWORK_GROUP" >>"$env_file"
  fi
  if [[ -n "$AGENT_LABELS" ]]; then
    write_env_var "LLM_AGENT_LABELS" "$AGENT_LABELS" >>"$env_file"
  fi
  if [[ -n "$AGENT_ENDPOINT_URL" ]]; then
    write_env_var "LLM_AGENT_ENDPOINT_URL" "$AGENT_ENDPOINT_URL" >>"$env_file"
  fi
  if [[ -n "$AGENT_ALLOWED_TARGETS" ]]; then
    write_env_var "LLM_AGENT_ALLOWED_TARGETS" "$AGENT_ALLOWED_TARGETS" >>"$env_file"
  fi
}

start_with_systemd() {
  local uv_bin="$1"
  local env_file="$2"
  local service_file="/etc/systemd/system/llm-api-factory-agent.service"

  cat >"$service_file" <<EOF
[Unit]
Description=LLM API Factory Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$INSTALL_DIR/backend
EnvironmentFile=$env_file
ExecStart=$uv_bin run llm-agent
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable --now llm-api-factory-agent.service
  systemctl --no-pager status llm-api-factory-agent.service || true
}

start_with_nohup() {
  local uv_bin="$1"
  local env_file="$2"
  local run_script="$INSTALL_DIR/run_agent.sh"
  local pid_file="$INSTALL_DIR/agent.pid"
  local log_file="$INSTALL_DIR/agent.log"

  cat >"$run_script" <<EOF
#!/usr/bin/env bash
set -euo pipefail
set -a
source "$env_file"
set +a
cd "$INSTALL_DIR/backend"
exec "$uv_bin" run llm-agent
EOF
  chmod +x "$run_script"

  if [[ -f "$pid_file" ]]; then
    local old_pid
    old_pid="$(cat "$pid_file" || true)"
    if [[ -n "$old_pid" ]] && kill -0 "$old_pid" 2>/dev/null; then
      kill "$old_pid" || true
      sleep 1
    fi
  fi

  nohup "$run_script" >"$log_file" 2>&1 &
  echo "$!" >"$pid_file"
  echo "Agent started with nohup. PID file: $pid_file"
  echo "Log file: $log_file"
}

install_system_packages_if_possible
require_command curl
sync_repo
install_uv_if_needed

UV_BIN="$(command -v uv)"
(
  cd "$INSTALL_DIR/backend"
  "$UV_BIN" sync --no-dev
)

if [[ "${EUID:-$(id -u)}" -eq 0 ]]; then
  ENV_FILE="/etc/llm-api-factory-agent.env"
else
  ENV_FILE="$INSTALL_DIR/.agent.env"
fi
write_env_file "$ENV_FILE"

if [[ "$NO_SYSTEMD" -eq 0 && "${EUID:-$(id -u)}" -eq 0 ]] && command -v systemctl >/dev/null 2>&1; then
  start_with_systemd "$UV_BIN" "$ENV_FILE"
else
  start_with_nohup "$UV_BIN" "$ENV_FILE"
fi

echo "Agent install complete: $AGENT_NAME"
